plugin:
  enable: true
  prefix: ""
  usage: "/report pseudo reason"
  no-console: "&cOnly player can use this command !"
  permission-denied: "You don't have this permission !"
gui:
  title: "§c GUI BasikReport"
  items-lores:
    - "reported {report_count} time"
message:
  player:
    report-confirmed: " Vous venez de report {player} !"
    report-failed: "&cLe joueur {player} est introuvable !"
  staff:
    report: "{player_reported} was reported by {player} for {reason}"
    report-list-row: "➥ {player} reported {report_counter}"
    report-list-empty: "Aucun joueur report"

